/**
 * Shared domain types. The database.types.ts file (generated by
 * `pnpm db:types`) is the source of truth for raw row shapes — these
 * are higher-level domain types used throughout the apps.
 */

export type Locale = 'fr' | 'ar';
export type AccountRole = 'sitter' | 'parent' | 'admin';

export type VerificationStatus = 'unverified' | 'pending' | 'verified' | 'rejected';

export interface Profile {
  id: string;                  // matches auth.users.id
  role: AccountRole;
  firstName: string;
  lastName: string;
  email: string;
  phone?: string;
  avatarUrl?: string;
  bio?: string;
  city?: string;
  wilaya?: string;             // Algerian province (Alger, Oran, Ouargla, ...)
  latitude?: number;
  longitude?: number;
  locale: Locale;
  idVerification: VerificationStatus;
  createdAt: string;
  updatedAt: string;
}

export interface SitterProfile extends Profile {
  role: 'sitter';
  hourlyRate?: number;         // DZD
  experienceYears?: number;
  languages: Locale[];
  ageGroups: AgeGroup[];       // age groups they care for
  services: SitterService[];
  availability?: WeeklyAvailability;
  ratingAverage?: number;
  ratingCount: number;
  hasCriminalRecord: VerificationStatus;
}

export interface ParentProfile extends Profile {
  role: 'parent';
  numberOfChildren?: number;
  children?: ChildSummary[];
}

export type AgeGroup = 'infant' | 'toddler' | 'preschool' | 'school' | 'teen';

export type SitterService =
  | 'babysitting'
  | 'nanny'
  | 'homework_help'
  | 'school_pickup'
  | 'overnight'
  | 'weekend'
  | 'special_needs';

export interface ChildSummary {
  ageGroup: AgeGroup;
  notes?: string;
}

export interface WeeklyAvailability {
  monday?: TimeRange[];
  tuesday?: TimeRange[];
  wednesday?: TimeRange[];
  thursday?: TimeRange[];
  friday?: TimeRange[];
  saturday?: TimeRange[];
  sunday?: TimeRange[];
}

export interface TimeRange { from: string; to: string; }  // "08:00", "17:30"

export interface Conversation {
  id: string;
  participantIds: string[];
  lastMessageAt: string;
  lastMessagePreview?: string;
  unreadCount: number;
}

export interface Message {
  id: string;
  conversationId: string;
  senderId: string;
  body: string;
  createdAt: string;
  readAt?: string;
}

export interface Booking {
  id: string;
  parentId: string;
  sitterId: string;
  status: 'pending' | 'accepted' | 'declined' | 'cancelled' | 'completed';
  startAt: string;
  endAt: string;
  notes?: string;
  hourlyRate?: number;
  totalAmount?: number;
  createdAt: string;
}

export interface Review {
  id: string;
  bookingId?: string;
  reviewerId: string;
  revieweeId: string;
  rating: 1 | 2 | 3 | 4 | 5;
  body?: string;
  createdAt: string;
}

export interface SearchFilters {
  query?: string;
  bounds?: { north: number; south: number; east: number; west: number };
  center?: { lat: number; lng: number; radiusKm?: number };
  services?: SitterService[];
  ageGroups?: AgeGroup[];
  languages?: Locale[];
  minRate?: number;
  maxRate?: number;
  minExperience?: number;
  verifiedOnly?: boolean;
}

/** Algerian wilayas (provinces) — used for filters and address suggestions. */
export const WILAYAS = [
  'Adrar', 'Chlef', 'Laghouat', 'Oum El Bouaghi', 'Batna', 'Béjaïa', 'Biskra',
  'Béchar', 'Blida', 'Bouira', 'Tamanrasset', 'Tébessa', 'Tlemcen', 'Tiaret',
  'Tizi Ouzou', 'Alger', 'Djelfa', 'Jijel', 'Sétif', 'Saïda', 'Skikda',
  'Sidi Bel Abbès', 'Annaba', 'Guelma', 'Constantine', 'Médéa', 'Mostaganem',
  "M'Sila", 'Mascara', 'Ouargla', 'Oran', 'El Bayadh', 'Illizi',
  'Bordj Bou Arréridj', 'Boumerdès', 'El Tarf', 'Tindouf', 'Tissemsilt',
  'El Oued', 'Khenchela', 'Souk Ahras', 'Tipaza', 'Mila', 'Aïn Defla',
  'Naâma', 'Aïn Témouchent', 'Ghardaïa', 'Relizane', 'Timimoun',
  'Bordj Badji Mokhtar', 'Ouled Djellal', 'Béni Abbès', 'In Salah',
  'In Guezzam', 'Touggourt', 'Djanet', "El M'Ghair", 'El Meniaa',
] as const;

export type Wilaya = (typeof WILAYAS)[number];
